  
apiVersion: config.anthos.dev/v1
kind: Config
metadata:
  name: nginx-config
spec:
  managementPolicy: auto
  resources:
  - apiVersion: apps/v1
    kind: Deployment
    name: nginx
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - name: nginx
            image: us-central1-docker.pkg.dev/proj-setup/anthos/anthos
            ports:
            - containerPort: 8080
            imagePullPolicy: Always
            env:
              - name: PORT
                value: "8080"        

  - apiVersion: v1
    kind: Service
    name: nginx
    spec:
      selector:
        app: nginx
      ports:
      - name: http
        port: 8080
        targetPort: 80
      type: LoadBalancer




